version: "3"
services:
  #
  # Works - but DB gets provided by dedicated hw
  #
  # db:
  #   image: mysql:latest
  #   container_name: fish_db
  #   environment:
  #     - MYSQL_DATABASE='fish_prod'
  #     - MYSQL_USER=mysql
  #     - MYSQL_PASSWORD=1pASSword!
  #   ports:
  #     - "3306:3306"
  #   expose:
  #     - "3306"
  #   volumes:
  #     - ./priv/repo/db:/var/lib/mysql
  #   networks:
  #     - db-network

  web:
    image: fish2
    # command: mix phx.server
    environment:
      - MIX_ENV=prod
      - APP_PORT=4000
      - POOL_SIZE=10
      - COOL_TEXT='HELLO'
      - SECRET_KEY_BASE="y9TbX7zNZ86omfNJtRUo6RgZj+WGYG9Hy5CGRBxUZR9gUdycueITq+BZOwv20czu"
      - DBUSER=xxx
      - DBPWRD=xxx
      - DBNAME=fish_prod
      # - DBHOST=db <- use this setup if you uncomment the db service
      - DBHOST=1.2.3.4
      - URLHOST=http://localhost
    volumes:
      - .:/opt/app
    ports:
      - "4000:4000"
#     links:
#       - db
#     depends_on:
#       - db
#     networks:
#       - db-network
# networks:
#   db-network:
